---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age1npdruy3nx2yr0h6yjmpffpsesszj7qldnsrpxt0sdrxwqsls85eq07l56y"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age1npdruy3nx2yr0h6yjmpffpsesszj7qldnsrpxt0sdrxwqsls85eq07l56y"
stores:
  yaml:
    indent: 2
